### ISSUE TITLE
UI 部分一点点闲话供参考

### ISSUE THREAD

**Issue by smart-z** [gaodeng/MoonFM#39]
感觉该UI的设计是一位非常棒非常新视野的设计；

字体大小的比例很精妙，但这个比例维持在界面字体大小很小的状态下阅读很费劲，字太小，颜色太浅，当然不同字体大小不同设计颜色是很精妙；建议整体放大1.15倍；眼睛会舒适一点，看的时候不那么费力，现在的界面看起来太耗神了。黑皮肤太黑呼呼，蓝皮肤太糊。
iOS 设计规范里面有一条是清晰锐利。iOS 11 之后部分页面在循环改版，字体和比例越来越大，这是时代趋势。这个年代大家都在看手机，大家的视力都不好。iOS的设计当然可以设计的很艺术， a new simple style 但是他没有这就是取舍。

唠叨几句，就不练提纲了，觉得有用可以看一看，没请忽略。

**Comment by gaodeng** [comment]
谢谢非常棒的建议👍，后面我会持续优化的。

**Comment by smart-z** [comment]
嘿嘿，赞赞赞
