### ISSUE TITLE
有添加 feed 地址到 Moon FM订阅的 url scheme 吗？

### ISSUE THREAD

**Issue by rpsh** [gaodeng/MoonFM#47]
像 Apple 播客是这种
podcast://www.ximalaya.com/album/3558668.xml

**Comment by gaodeng** [comment]
@rpsh   目前版本还没。下个版本会添加
moonfm://subscribe?url=https://getpodcast.xyz/data/ximalaya/5574153.xml

你是 podcast.xyz 的大佬吗，前几天还想到时候联系你们，看看能不能把 Moon FM 也加上去呀。

**Comment by rpsh** [comment]
嗯。 getpodcast.xyz 是我的一个小项目。
这个 URL Scheme 可用了，可以通知我一下，我加上
